// Import necessary modules and components
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Sidebar from "../../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <main className="md:hidden">
          {/* <Sidebar /> */}
          <Navbar />
          {children}
        </main>
        <div className="hidden w-full h-screen md:flex md:justify-center md:items-center">
          <span className="text-center font-bold text-4xl">Nous ne sommes disponibles que sur Smartphone!</span>
        </div>
      </body>
    </html>
  );
}
